version: '3'
volumes:
  persistent:

services:
  bot:
    build: .
    restart: always
    volumes:
      - ${RECORDINGS_PATH:?Path on the disk where to store ready recordings}:/recordings:rw
      - persistent:/persistent:rw